In [71]:
import pandas as pd
import numpy as np
import wrds
import nasdaqdatalink as ndl

import keys

# 0. S&P500 Ticker List

https://github.com/fja05680/sp500

- ./data/sp500_tickers/sp500.csv : current sp500 components
- ./data/sp500_tickers/sp500_historical.csv : tickers from 1996 to 2023

In [85]:
tickers = pd.read_csv("./data/sp500_tickers/sp500_historical.csv")
tickers.shape

(2666, 2)

In [86]:
tickers

            date                                            tickers
0     1996-01-02  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...
1     1996-01-03  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...
2     1996-01-04  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...
3     1996-01-10  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...
4     1996-01-11  AAL,AAMRQ,AAPL,ABI,ABS,ABT,ABX,ACKH,ACV,ADM,AD...
...          ...                                                ...
2661  2022-12-19  A,AAL,AAP,AAPL,ABBV,ABC,ABMD,ABT,ACGL,ACN,ADBE...
2662  2022-12-22  A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACGL,ACN,ADBE,ADI,...
2663  2023-01-04  A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACGL,ACN,ADBE,ADI,...
2664  2023-03-15  A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACGL,ACN,ADBE,ADI,...
2665  2023-03-20  A,AAL,AAP,AAPL,ABBV,ABC,ABT,ACGL,ACN,ADBE,ADI,...

[2666 rows x 2 columns]

# 1. WRDS

In [57]:
conn = wrds.Connection(wrds_username = "younghunlee")

Loading library list...
Done

In [67]:
# conn.list_libraries()
# conn.list_tables(library = "wrdsapps")

In [65]:
query = """SELECT * 
    FROM wrdsapps_finratio.firm_ratio 
    WHERE ticker = 'AAPL' 
    AND adate >= '2010-01-01' AND adate <= '2019-12-31'
    ORDER BY adate ASC;"""

- public_date : market available date
- gsesector : GICS industry portfolio value
- gsedecs: GICS sector name

In [66]:
temp = conn.raw_sql(query)
temp

,gvkey,permno,adate,qdate,public_date,capei,be,bm,evm,pe_op_basic,...,ffi30_desc,ffi30,ffi38_desc,ffi38,ffi48_desc,ffi48,ffi49_desc,ffi49,ticker,cusip
0,001690,14593.0,2010-09-30,2010-09-30,2010-11-30,43.820442,52091.0,0.200422,13.454806,20.270358,...,BUSEQ,23.0,MACHN,21.0,COMPS,35.0,HARDW,35.0,AAPL,03783310
1,001690,14593.0,2010-09-30,2010-09-30,2010-12-31,45.611976,52091.0,0.200422,13.454806,21.013681,...,BUSEQ,23.0,MACHN,21.0,COMPS,35.0,HARDW,35.0,AAPL,03783310
2,001690,14593.0,2010-09-30,2010-09-30,2011-01-31,47.994605,52091.0,0.200422,13.454806,22.105537,...,BUSEQ,23.0,MACHN,21.0,COMPS,35.0,HARDW,35.0,AAPL,03783310
3,001690,14593.0,2010-09-30,2010-12-31,2011-02-28,52.059321,60084.0,0.202242,11.037996,0.695405,...,BUSEQ,23.0,MACHN,21.0,COMPS,35.0,HARDW,35.0,AAPL,03783310
4,001690,14593.0,2010-09-30,2010-12-31,2011-03-31,51.555571,60084.0,0.202242,11.037996,0.686146,...,BUSEQ,23.0,MACHN,21.0,COMPS,35.0,HARDW,35.0,AAPL,03783310
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,001690,14593.0,2019-09-30,2020-03-31,2020-06-30,29.774032,78425.0,0.071325,15.300343,7.080745,...,BUSEQ,23.0,ELCTR,22.0,CHIPS,36.0,CHIPS,37.0,AAPL,03783310
116,001690,14593.0,2019-09-30,2020-03-31,2020-07-31,34.623415,78425.0,0.071325,15.300343,8.250000,...,BUSEQ,23.0,ELCTR,22.0,CHIPS,36.0,CHIPS,37.0,AAPL,03783310
117,001690,14593.0,2019-09-30,2020-06-30,2020-08-31,41.740324,72282.0,0.046252,17.194606,9.702256,...,BUSEQ,23.0,ELCTR,22.0,CHIPS,36.0,CHIPS,37.0,AAPL,03783310
118,001690,14593.0,2019-09-30,2020-06-30,2020-09-30,37.185353,72282.0,0.046252,17.194606,8.707519,...,BUSEQ,23.0,ELCTR,22.0,CHIPS,36.0,CHIPS,37.0,AAPL,03783310
119,001690,14593.0,2019-09-30,2020-06-30,2020-10-31,35.005337,72282.0,0.046252,17.194606,8.184962,...,BUSEQ,23.0,ELCTR,22.0,CHIPS,36.0,CHIPS,37.0,AAPL,03783310

In [68]:
temp.columns

Index(['gvkey', 'permno', 'adate', 'qdate', 'public_date', 'capei', 'be', 'bm',
       'evm', 'pe_op_basic', 'pe_op_dil', 'pe_exi', 'pe_inc', 'ps', 'pcf',
       'dpr', 'npm', 'opmbd', 'opmad', 'gpm', 'ptpm', 'cfm', 'roa', 'roe',
       'roce', 'efftax', 'aftret_eq', 'aftret_invcapx', 'aftret_equity',
       'pretret_noa', 'pretret_earnat', 'gprof', 'equity_invcap',
       'debt_invcap', 'totdebt_invcap', 'capital_ratio', 'int_debt',
       'int_totdebt', 'cash_lt', 'invt_act', 'rect_act', 'debt_at',
       'debt_ebitda', 'short_debt', 'curr_debt', 'lt_debt', 'profit_lct',
       'ocf_lct', 'cash_debt', 'fcf_ocf', 'lt_ppent', 'dltt_be', 'debt_assets',
       'debt_capital', 'de_ratio', 'intcov', 'intcov_ratio', 'cash_ratio',
       'quick_ratio', 'curr_ratio', 'cash_conversion', 'inv_turn', 'at_turn',
       'rect_turn', 'pay_turn', 'sale_invcap', 'sale_equity', 'sale_nwc',
       'rd_sale', 'adv_sale', 'staff_sale', 'accrual', 'ret_crsp', 'gsector',
       'gicdesc', 'mktcap', 'price', 'ptb', 'peg_trailing', 'divyield',
       'ffi5_desc', 'ffi5', 'ffi10_desc', 'ffi10', 'ffi12_desc', 'ffi12',
       'ffi17_desc', 'ffi17', 'ffi30_desc', 'ffi30', 'ffi38_desc', 'ffi38',
       'ffi48_desc', 'ffi48', 'ffi49_desc', 'ffi49', 'ticker', 'cusip'],
      dtype='object')

# 2. NasdaqDataLink

In [78]:
try:
    zacks_tickers = pd.read_csv('./data/zacks_tickers.csv')
except:
    zacks_tickers = ndl.get_table('ZACKS/MT', paginate = True)
    zacks_tickers = zacks_tickers[(zacks_tickers.active_ticker_flag == 'Y') & (zacks_tickers.country_code == 'US')]
    zacks_tickers = zacks_tickers[~zacks_tickers.zacks_x_sector_desc.isin(["Auto/Tires/Trucks", "Finance"])]
    zacks_tickers.to_csv('./data/zacks_tickers.csv')
zacks_tickers = zacks_tickers.ticker.unique()
ticker_avail = ','.join(zacks_tickers)

In [73]:
tickers

,m_ticker,ticker,comp_name,comp_name_2,exchange,currency_code,ticker_type,active_ticker_flag,comp_url,sic_4_code,...,per_end_month_nbr,mr_split_date,mr_split_factor,comp_cik,country_code,country_name,comp_type,optionable_flag,sp500_member_flag,asset_type
None,,,,,,,,,,,,,,,,,,,,,
1,ZYXI,ZYXI,Zynex,Zynex Inc.,NASDAQ,USD,S,Y,http://www.zynex.com,3845.0,...,12,2022-01-05,1.10,0000846475,US,UNITED STATES,1.0,Y,N,COM
3,ZYNE,ZYNE,Zynerba Pharmaceuticals,"Zynerba Pharmaceuticals, Inc.",NASDAQ,USD,S,Y,http://www.zynerba.com,2834.0,...,12,NaT,NaN,0001621443,US,UNITED STATES,1.0,Y,N,COM
8,ZY,TJX,The TJX Companies,"The TJX Companies, Inc.",NYSE,USD,S,Y,http://www.tjx.com,5651.0,...,1,2018-11-07,2.00,0000109198,US,UNITED STATES,1.0,Y,Y,COM
13,ZVIA,ZVIA,Zevia,Zevia PBC,NYSE,USD,S,Y,http://www.zevia.com,2086.0,...,12,NaT,NaN,0001854139,US,UNITED STATES,1.0,Y,N,COM
14,ZUO,ZUO,Zuora,"Zuora, Inc.",NYSE,USD,S,Y,http://www.zuora.com,7372.0,...,1,NaT,NaN,0001423774,US,UNITED STATES,1.0,Y,N,COM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38183,AACI,AACI,Armada Acquisition Corp. I,Armada Acquisition Corp. I,NASDAQ,USD,S,Y,None,6770.0,...,9,NaT,NaN,None,US,UNITED STATES,1.0,N,N,COM
38187,AAC4,AAC,Ares Acquisition Corp.,Ares Acquisition Corporation,NYSE,USD,S,Y,http://www.aresacquisitioncorporation.com,3443.0,...,12,NaT,NaN,None,US,UNITED STATES,1.0,Y,N,COM
38199,AA2,AA,Alcoa,Alcoa,NYSE,USD,S,Y,http://www.alcoa.com,3334.0,...,12,NaT,NaN,0001675149,US,UNITED STATES,1.0,Y,N,COM
38200,AA,HWM,Howmet Aerospace,Howmet Aerospace Inc.,NYSE,USD,S,Y,http://www.howmet.com,3350.0,...,12,2016-10-06,0.33,0000004281,US,UNITED STATES,1.0,Y,Y,COM
38201,A2,A,Agilent Technologies,"Agilent Technologies, Inc.",NYSE,USD,S,Y,http://www.agilent.com,3826.0,...,10,NaT,NaN,0001090872,US,UNITED STATES,1.0,Y,Y,COM

In [ ]:
start_date = '2014-08-01'
end_date = '2022-01-31'

try:
    fr = pd.read_csv("../data/zacks/fr.csv")
    fc = pd.read_csv("../data/zacks/fc.csv")
    mkval = pd.read_csv("../data/zacks/mktv.csv")
    shrs = pd.read_csv("../data/zacks/shrs.csv")
except:
    ndl.export_table('ZACKS/FR', ticker = ticker_avail, per_end_date = {'gte': start_date, 'lte': end_date }, filename = '../data/zacks/ZACKS_FR.zip')
    ndl.export_table('ZACKS/FC', ticker = ticker_avail, per_end_date = {'gte': start_date, 'lte': end_date }, filename = '../data/zacks/ZACKS_FC.zip')
    ndl.export_table('ZACKS/MKTV', ticker = ticker_avail, per_end_date = {'gte': start_date, 'lte': end_date }, filename = '../data/zacks/ZACKS_mktv.zip')
    ndl.export_table('ZACKS/SHRS', ticker = ticker_avail, per_end_date = {'gte': start_date, 'lte': end_date }, filename = '../data/zacks/ZACKS_shares.zip')